Assert model is non null
Without this assertion the app crashes with a cryptic error message when subscribing for changes. It should be impossible to create a scope with a `null` model to prevent such crashes early on.

### Before
```
The following NoSuchMethodError was thrown building ScopedModel<MyModel>:
The method 'addListener' was called on null.
Receiver: null
Tried calling: addListener(Closure: () => void from Function '_onChange@616019834':.)
```

### Now
```
The following assertion was thrown building SomeWidget(dirty, state: _SomeWidgetState#d0c78):
'package:myapp/model.dart': Failed assertion: line 78 pos 50: 'model != null': is not true.
```